apiVersion: v1
kind: Service
metadata:
  name: frontend-ci-service
  labels:
    app: frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: frontend-svc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080