apiVersion: v1
kind: Service
metadata:
  name: simple-lb-service
  labels:
    app: super-simple-svc
spec:
  type: LoadBalancer
  selector:
    app: super-simple-svc
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080