apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-simple-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: super-simple-svc
  template:
    metadata:
      labels:
        app: super-simple-svc
    spec:
      containers:
      - image: gcr.io/demoneil/ccg-demo:latest
        name: super-simple-svc-0